apiVersion: gcp.vault.upbound.io/v1alpha1
kind: SecretImpersonatedAccount
metadata:
  annotations:
    meta.upbound.io/example-id: gcp/v1alpha1/secretimpersonatedaccount
  labels:
    testing.upbound.io/example-name: impersonated_account
  name: impersonated-account
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: gcp
    impersonatedAccount: this
    serviceAccountEmail: ${google_service_account.this.email}
    tokenScopes:
    - https://www.googleapis.com/auth/cloud-platform

---

apiVersion: gcp.vault.upbound.io/v1alpha1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: gcp/v1alpha1/secretimpersonatedaccount
  labels:
    testing.upbound.io/example-name: gcp
  name: gcp
spec:
  forProvider:
    credentialsSecretRef:
      key: attribute.credentials.json
      name: example-secret
      namespace: upbound-system
    path: gcp
