apiVersion: aws.vault.upbound.io/v1alpha1
kind: AuthBackendClient
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1alpha1/authbackendclient
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    accessKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    secretKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system

---

apiVersion: auth.vault.upbound.io/v1alpha1
kind: Backend
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1alpha1/authbackendclient
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    type: aws
