apiVersion: ssh.vault.upbound.io/v1alpha1
kind: SecretBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: ssh/v1alpha1/secretbackendrole
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    allowUserCertificates: true
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    keyType: ca
    name: my-role

---

apiVersion: vault.vault.upbound.io/v1alpha1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: ssh/v1alpha1/secretbackendrole
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    type: ssh
