apiVersion: vault.vault.upbound.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: vault/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: dev-team
    policy: |
      path "secret/my_app" {
        capabilities = ["update"]
      }
