name: End to End Testing

on:
  issue_comment:
    types: [created]

jobs:
  e2e:
    uses: upbound/uptest/.github/workflows/pr-comment-trigger.yml@main
    with:
      go-version: '1.21'
    secrets:
      UPTEST_CLOUD_CREDENTIALS: "not used"
      UPTEST_DATASOURCE: ${{ secrets.UPTEST_DATASOURCE }}
